CREATE TABLE `rss` (
	`sn` INT(11) NOT NULL AUTO_INCREMENT,
	`file` VARCHAR(50) NOT NULL,
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`title` VARCHAR(200) NULL DEFAULT NULL,
	`text` MEDIUMTEXT NULL,
	`category` VARCHAR(50) NULL DEFAULT NULL,
	`url` VARCHAR(50) NOT NULL,
	`pubdate` TIMESTAMP NULL DEFAULT NULL,
	`author` VARCHAR(20) NULL DEFAULT NULL,
	`reply` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`recom` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`url`),
	INDEX `inx_sn` (`sn`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2101
;
